create database food_app_db
    with owner postgres;

create sequence public.privilege_seq
    increment by 50;

alter sequence public.privilege_seq owner to postgres;

create sequence public.role_seq
    increment by 50;

alter sequence public.role_seq owner to postgres;

create sequence public.users_seq
    increment by 50;

alter sequence public.users_seq owner to postgres;

create table public.app_settings
(
    id                   bigint not null
        primary key,
    created_at           timestamp(6) with time zone,
    created_by           varchar(255),
    last_modified_at     timestamp(6) with time zone,
    last_modified_by     varchar(255),
    address              varchar(255),
    company_name         varchar(255),
    food_prices_active   boolean,
    phone                varchar(255),
    employee_price_share integer,
    employer_price_share integer,
    reservation_hour     integer,
    reservation_minute   integer,
    version              bigint
);

alter table public.app_settings
    owner to postgres;

create table public.cost_center
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

alter table public.cost_center
    owner to postgres;

create table public.daily_meal
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone,
    created_by       varchar(255),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(255),
    meal_date        date    not null,
    jalali_day       integer not null,
    jalali_month     integer not null,
    jalali_year      integer not null
);

alter table public.daily_meal
    owner to postgres;

create table public.dish
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone,
    created_by       varchar(255),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(255),
    name             varchar(255) not null,
    price            integer
);

alter table public.dish
    owner to postgres;

create table public.daily_meal_dish
(
    id            bigint generated by default as identity
        primary key,
    daily_meal_id bigint
        constraint fkq9j6gh7in6aj7eagonnem9l57
            references public.daily_meal,
    dish_id       bigint
        constraint fk36m3lpjtg76qdugpexp5k5amw
            references public.dish
);

alter table public.daily_meal_dish
    owner to postgres;

create table public.guest
(
    id                 bigint generated by default as identity
        primary key,
    first_name         char(255),
    last_name          char(255),
    cost_center_id     bigint
        constraint fkf20d3xa5tpcy1xaca1m7q3f67
            references public.cost_center,
    daily_meal_dish_id bigint not null
        constraint fkeex8vywx6nrjuqnpvcji5fchn
            references public.daily_meal_dish
);

alter table public.guest
    owner to postgres;

create table public.personnel
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone,
    created_by       varchar(255),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(255),
    first_name       varchar(255) not null,
    last_name        varchar(255) not null,
    password         varchar(255),
    pers_code        varchar(255) not null,
    username         varchar(255) not null
);

alter table public.personnel
    owner to postgres;

create table public.privilege
(
    id   bigint not null
        primary key,
    name varchar(255)
);

alter table public.privilege
    owner to postgres;

create table public.reservation
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone,
    created_by         varchar(255),
    last_modified_at   timestamp(6) with time zone,
    last_modified_by   varchar(255),
    reservation_status varchar(255) not null
        constraint reservation_reservation_status_check
            check ((reservation_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'DELIVERED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])),
    reservation_time   timestamp(6) not null,
    daily_meal_id      bigint       not null
        constraint fkrcuei1va19o702gkxpeie7gsk
            references public.daily_meal,
    daily_meal_dish_id bigint       not null
        constraint fkghiayhtg3ophqdytxg8lsecf7
            references public.daily_meal_dish,
    personnel_id       bigint       not null
        constraint fkmvfj6c6ir3ssgqdwi5cxgx5n8
            references public.personnel
);

alter table public.reservation
    owner to postgres;

create table public.cost_shares
(
    id                        bigint generated by default as identity
        primary key,
    employee_portion          numeric(10, 2),
    employee_share_percentage numeric(5, 2),
    employer_portion          numeric(10, 2),
    quantity                  integer not null,
    total_cost                numeric(10, 2),
    reservation_id            bigint  not null
        constraint uksuahlo9llk68sbfhym4xwrdv1
            unique
        constraint fkcvnipggvtvihoh49p9nf7n0ql
            references public.reservation
);

alter table public.cost_shares
    owner to postgres;

create table public.role
(
    id   bigint not null
        primary key,
    name varchar(255)
);

alter table public.role
    owner to postgres;

create table public.roles_privileges
(
    role_id      bigint not null
        constraint fk9h2vewsqh8luhfq71xokh4who
            references public.role,
    privilege_id bigint not null
        constraint fk5yjwxw2gvfyu76j3rgqwo685u
            references public.privilege
);

alter table public.roles_privileges
    owner to postgres;

create table public.users
(
    id                  bigint       not null
        primary key,
    account_expired     boolean      not null,
    account_locked      boolean      not null,
    credentials_expired boolean      not null,
    employee_code       varchar(255)
        constraint ukob2dx53vn966ek0roock2539f
            unique,
    enabled             boolean      not null,
    first_name          varchar(255),
    last_name           varchar(255),
    password            varchar(255) not null,
    token_expired       boolean      not null,
    username            varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table public.users
    owner to postgres;

create table public.users_roles
(
    user_id bigint not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references public.users,
    role_id bigint not null
        constraint fkt4v0rrweyk393bdgt107vdx0x
            references public.role
);

alter table public.users_roles
    owner to postgres;

